---
javascripts:
- base:
  - libs/jquery-1.3.2
  - libs/jquery-ui-1.7.2.min
  - libs/jquery.form
  - libs/jquery.spinner
  - libs/jquery.blueprint.showgrid
  - libs/jquery.validationEngine
  - libs/jquery.colorpicker
  - libs/jquery.inputHint
  - libs/underscore
  - application.en-US
stylesheets:
- base_screen:
  - blueprint/reset
  - blueprint/typography
  - blueprint/grid
  - blueprint/forms
  - blueprint/buttons/screen
  - blueprint/fancy-type/screen
  - jquery-ui-1.7.2
  - validationEngine.jquery
  - colorpicker
  - compiled/breadcrumb
  - compiled/spinner
- base_print:
  - blueprint/print

