---
javascripts:
- base:
  - prototype
  - effects
  - dragdrop
  - controls
  - lowpro
  - routes
  - application
stylesheets:
- base_screen:
  - blueprint/screen
  - blueprint/ie
  - blueprint/buttons/screen
  - blueprint/fancy-type/screen
- base_print:
  - blueprint/print

