---
javascripts:
- base:
  - libs/jquery-1.3.2
  - libs/jquery-ui-1.7.2.min
  - libs/jquery.form
  - libs/jquery.spinner
  - libs/jquery.blueprint.showgrid
  - libs/jquery.validationEngine
  - application.en-US
stylesheets:
- base_screen:
  - blueprint/screen
  - blueprint/ie
  - blueprint/buttons/screen
  - blueprint/fancy-type/screen
  - jquery-ui-1.7.2
  - validationEngine.jquery
  - spinner
- base_print:
  - blueprint/print

