---
javascripts:
- base:
  - jquery-1.3.2
  - jquery-ui-1.7.2.min
  - jquery.form
  - jquery.spinner
  - jquery.blueprint.showgrid
  - jquery.validationEngine
  - routes
  - application.en-US
stylesheets:
- base_screen:
  - blueprint/screen
  - blueprint/ie
  - blueprint/buttons/screen
  - blueprint/fancy-type/screen
  - jquery-ui-1.7.2
  - validationEngine.jquery
  - spinner
- base_print:
  - blueprint/print

